services:

  ai-web-starter:
    build:
      context: web
      args:
        - REACT_APP_API_URL=http://localhost:8000
    ports:
      - "8080:80"
    depends_on:
      - ai-backend-starter

  ai-backend-starter:
    build:
      context: backend
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: "localhost"
      CORS_ALLOWED_ORIGINS: "http://localhost:8080"
      DATABASE_URL: "postgres://root:changeMe!@db:5432/ai-starter"

  db:
    image: postgres:14.12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ai-starter
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeMe!
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres_data:
