services:

  ai-web-starter:
    build:
      context: web
    depends_on:
      - ai-backend-starter

  ai-backend-starter:
    build:
      context: backend
    ports:
      - "8000:8000"
    environment:
      ALLOWED_HOSTS: '*,'
      CORS_ALLOW_ALL_ORIGINS: "True"
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      MISTRAL_API_KEY: ${MISTRAL_API_KEY}
      HUGGINGFACE_API_KEY: ${HUGGINGFACE_API_KEY}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      DEFAULT_FROM_EMAIL: ${DEFAULT_FROM_EMAIL}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
