# Generated by Django 5.0.3 on 2024-04-10 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aiModule", "0002_message"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="rawText",
            new_name="prompt",
        ),
    ]
