# Generated by Django 5.0.3 on 2024-04-10 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiModule', '0004_message_generatedreply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='chatHistory',
        ),
        migrations.AddField(
            model_name='conversation',
            name='chatHistory',
            field=models.TextField(blank=True, null=True),
        ),
    ]
