# Generated by Django 5.0.3 on 2024-04-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aiModule", "0009_alter_conversation_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmconfiguration",
            name="owner",
        ),
    ]
