# Generated by Django 5.0.3 on 2024-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aiModule", "0015_courseenrollment_student_alter_course_createdby"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="slides",
            field=models.TextField(max_length=99999, null=True),
        ),
    ]
