# Generated by Django 5.0.3 on 2024-05-01 00:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aiModule", "0019_conversation_course_creation_tokens"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="categoryId",
        ),
        migrations.RemoveField(
            model_name="course",
            name="dateCreated",
        ),
        migrations.RemoveField(
            model_name="course",
            name="description",
        ),
        migrations.RemoveField(
            model_name="course",
            name="name",
        ),
        migrations.CreateModel(
            name="CourseOffering",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=256, null=True)),
                ("name", models.CharField(max_length=256, null=True)),
                ("categoryId", models.CharField(max_length=256)),
                (
                    "description",
                    models.TextField(blank=True, max_length=512, null=True),
                ),
                (
                    "dateCreated",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("level", models.IntegerField(blank=True, default=0, null=True)),
                ("imageURL", models.CharField(max_length=256, null=True)),
                (
                    "polymorphic_ctype",
                    models.ForeignKey(
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymorphic_%(app_label)s.%(class)s_set+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "base_manager_name": "objects",
            },
        ),
        migrations.AddField(
            model_name="course",
            name="courseOffering",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="createdCourses",
                to="aiModule.courseoffering",
            ),
        ),
    ]
