# Generated by Django 5.0.3 on 2024-05-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiModule', '0022_remove_course_courseoffering_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
