# Generated by Django 5.0.3 on 2024-05-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aiModule", "0024_course_curriculum"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="curriculum",
            new_name="lessonPlan",
        ),
    ]
