# Generated by Django 5.0.3 on 2024-05-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("aiModule", "0025_rename_curriculum_course_lessonplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="lesson_gen_tokens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
