# Generated by Django 5.0.3 on 2024-05-10 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiModule', '0029_course_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseenrollment',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
