# Generated by Django 5.0.3 on 2024-05-14 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aiModule', '0030_courseenrollment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='IndexError',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
