# Generated by Django 5.0.3 on 2024-05-14 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aiModule', '0031_lesson_indexerror'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='IndexError',
            new_name='index',
        ),
    ]
