# Generated by Django 5.0.3 on 2024-05-16 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("aiModule", "0032_rename_indexerror_lesson_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courseenrollment",
            name="course",
        ),
        migrations.RemoveField(
            model_name="courseenrollment",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="courseenrollment",
            name="student",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="polymorphic_ctype",
        ),
        migrations.RemoveField(
            model_name="conversation",
            name="course_creation_tokens",
        ),
        migrations.RemoveField(
            model_name="message",
            name="functionData",
        ),
        migrations.RemoveField(
            model_name="message",
            name="functionType",
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.DeleteModel(
            name="CourseEnrollment",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
    ]
