export const defaultTheme = {
  backgroundColor: "#FFFFFF",
  borderColor: "#000000",
  textColor: "#000000",
  cardBackground: "#D6D6D6",
  primaryActionColor: "#B5B5B5",
  primaryActionHoverColor: "#BBBBBB",
  primaryActionBorder: "#CCCCCC",
  primaryTextColor: "#000000",
  secondaryTextColor: "#FFFFF",
  secondaryActionColor: "#FFFFFF",
  secondaryActionHoverColor: "#EEEEEE",
  secondaryBackground: "#F3F3F3",
  optionSelectedBackground: "#D3D3D3",
  optionUnselectedBackground: "#FFFFFF",
  iconColor: "#F3F3F3",
  error: "#ff0000",
};

export const darkTheme = {
  backgroundColor: "#1B1B1B",
  borderColor: "#FFFFFF",
  textColor: "#FFFFFF",
  cardBackground: "#D3D3D3",
  primaryActionColor: "#555555",
  primaryActionHoverColor: "#888888",
  primaryActionBorder: "#CCCCCC",
  primaryTextColor: "#FFFFFF",
  secondaryTextColor: "#000000",
  secondaryActionColor: "#FFFFFF",
  secondaryActionHoverColor: "#EEEEEE",
  secondaryBackground: "#333333",
  optionSelectedBackground: "#A3A3A3",
  optionUnselectedBackground: "#FFFFFF",
  iconColor: "#333333",
  error: "#ff0000",
};

export const blueTheme = {
  backgroundColor: "#E0F7FA",
  borderColor: "#0288D1",
  textColor: "#01579B",
  cardBackground: "#B3E5FC",
  primaryActionColor: "#0277BD",
  primaryActionHoverColor: "#01579B",
  primaryActionBorder: "#CCCCCC",
  primaryTextColor: "#FFFFFF",
  secondaryTextColor: "#01579B",
  secondaryActionColor: "#B3E5FC",
  secondaryActionHoverColor: "#81D4FA",
  secondaryBackground: "#E1F5FE",
  optionSelectedBackground: "#B3E5FC",
  optionUnselectedBackground: "#FFFFFF",
  iconColor: "#0277BD",
  error: "#ff0000",
};
