# Generated by Django 5.0.3 on 2024-06-11 22:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=24, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('email_verification_code', models.CharField(blank=True, max_length=128, null=True)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('temp_password', models.CharField(blank=True, max_length=128, null=True)),
                ('metadata', models.TextField(blank=True, null=True)),
                ('change_temp_password', models.BooleanField(blank=True, default=False, null=True)),
                ('subscription', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
