# Generated by Django 5.0.3 on 2024-04-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_profile_temppassword"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="emailVerificationCode",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
