# Generated by Django 5.0.3 on 2024-04-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='metadata',
            field=models.TextField(blank=True, null=True),
        ),
    ]
