# Generated by Django 5.0.3 on 2024-04-08 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_profile_metadata"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="changeTempPassword",
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
