# Generated by Django 5.0.3 on 2024-05-05 19:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_profile_emailverificationcode"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="subscription",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
